# Basic
title: Zuo Wang
subtitle: Personal Blog
description: Welcome to my blog~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: zuowang
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: æœºå™¨è§†è§‰ / æ·±åº¦å­¦ä¹ 
url: "zuowang.github.io"

# Comment
comment:
    # disqus: leopard
    duoshuo: leopard 

# Social
social:
    weibo: harpe1999
    github: zuowang
    # twitter: 
    mail: wangzuo.nj@qq.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: c203919e27e0eb1440cf4bf28dc8aa44

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
#    id: UA-84134159-3   
#    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: index

# Navigation buttons in the front page.s
nav:
    - {title: archive, description: archive, url: '/archive'}   
    - {title: tags, description: tags, url: '/tags'}      
    - {title: about, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


